---
branches:
  only:
    - master

services:
  - docker

env:
  - distro: wheezy
    init: ""
    run_opts: ""
  - distro: jessie
    init: ""
    run_opts: ""
  - distro: centos7
    init: /usr/sbin/init
    run_opts: "--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro"

before_script:
  - >
    docker build --pull --no-cache -t ansible-roles-test-${distro}
    -f tests/support/${distro}.Dockerfile tests/support

script:
  - >
    docker run -d -it ${run_opts} --name ${distro}
    -v $PWD:/etc/ansible/roles/mongodb
    --workdir /etc/ansible/roles/mongodb/tests
    ansible-roles-test-${distro} ${init}
  - DOCKER_CONTAINER_ID=$(docker ps --filter name=${distro} -q)
  - >
    docker exec -it $DOCKER_CONTAINER_ID
    /bin/bash -xec "bash -x support/run-tests.sh"
